"""Editorial overrides for the main Marathi and Hindi museum interface."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
overrides={
'mr':{
'Explore archive':'संग्रह शोधा','History map':'इतिहासाचा प्रवास','Media library':'माध्यम संग्रह','Research assistant':'संशोधन सहाय्यक','Institution console':'संस्थेचे व्यवस्थापन','Install app':'ॲप इन्स्टॉल करा','Choose language':'भाषा निवडा',
'AMBEDKAR DIGITAL ARCHIVE':'आंबेडकर डिजिटल संग्रह','KNOWLEDGE · JUSTICE · MEMORY':'ज्ञान · न्याय · स्मृती','Ideas that shaped':'आधुनिक भारताला','modern India.':'आकार देणारे विचार.',
'Explore the writings, speeches and constitutional vision of Dr. B. R. Ambedkar through a living, evidence-led digital archive.':'डॉ. बाबासाहेब आंबेडकरांचे लेखन, भाषणे आणि संविधानविषयक विचार मूळ संदर्भांसह या डिजिटल संग्रहातून जाणून घ्या.',
'Search speeches, ideas, dates…':'भाषणे, विचार किंवा तारखा शोधा…','Explore':'शोधा','Begin with':'येथून सुरुवात करा','Constitution':'संविधान','Social democracy':'सामाजिक लोकशाही','Annihilation of Caste':'जातिव्यवस्थेचे निर्मूलन',
'Educate,':'शिका,','agitate,':'संघर्ष करा,','organise.':'संघटित व्हा.','DR. B. R. AMBEDKAR':'डॉ. बाबासाहेब आंबेडकर','Portrait dated 17 January 1935':'१७ जानेवारी १९३५ रोजीचे छायाचित्र','Public domain · Wikimedia Commons':'सार्वजनिक मालकी · Wikimedia Commons',
'Not just an archive.':'एक संग्रह आणि त्याही पलीकडे.','A place to question, listen':'प्रश्न विचारण्यासाठी, ऐकण्यासाठी','and understand.':'आणि समजून घेण्यासाठी.',
'CURATED RECORDS':'निवडक नोंदी','LANGUAGES':'भाषा','CORE PERIOD':'मुख्य कालखंड','SOURCE LINKED':'मूळ संदर्भांसह','PHOTOGRAPHS IN CONTEXT':'संदर्भांसह छायाचित्रे','Witnesses to history.':'इतिहासाचे साक्षीदार.','Open the history map':'इतिहासाचा प्रवास पाहा','CURATED JOURNEYS':'निवडक प्रवास','Choose a way in.':'तुमचा प्रवास निवडा.','View all collections':'सर्व संग्रह पाहा',
'FEATURED RECORD':'विशेष नोंद','The final warning':'अंतिम इशारा','Open the speech':'भाषण उघडा','ON-SITE EXPERIENCE':'संग्रहालयातील अनुभव','Launch kiosk mode':'किऑस्क सुरू करा','Exit kiosk mode':'किऑस्कमधून बाहेर पडा','Open media library':'माध्यम संग्रह उघडा','Turn this screen into a museum kiosk.':'या स्क्रीनवर संग्रहालयाचा किऑस्क सुरू करा.',
'EXPLORE YOUR WAY':'तुमच्या पद्धतीने जाणून घ्या','Search. Study. Listen. Compile.':'शोधा. अभ्यास करा. ऐका. संग्रह तयार करा.','Search':'शोधा','Study':'अभ्यास करा','Listen':'ऐका','Compile':'संग्रह तयार करा','ASK THE ARCHIVE':'संग्रहाला विचारा','Ask SMRITI':'SMRITI ला विचारा','What did Ambedkar mean':'आंबेडकरांना नेमके काय अभिप्रेत होते','by social democracy?':'सामाजिक लोकशाही म्हणजे?',
'THE COLLECTION':'संग्रह','Explore the archive':'संग्रह शोधा','Search source-linked writings, speeches, debates and manuscripts.':'मूळ संदर्भांसह लेखन, भाषणे, वादविवाद आणि हस्तलिखिते शोधा.','Search by title, theme or date…':'शीर्षक, विषय किंवा तारखेनुसार शोधा…','records':'नोंदी','All records':'सर्व नोंदी','Writings':'लेखन','Speeches':'भाषणे','Caste':'जात','Buddhism':'बौद्ध धर्म','Clear search':'शोध पुसा','No record matches “':'कोणतीही नोंद सापडली नाही: “',
'The lifetime history map':'जीवनप्रवास आणि इतिहास','All history':'संपूर्ण इतिहास','Life & education':'जीवन आणि शिक्षण','Books':'पुस्तके','Articles & essays':'लेख आणि निबंध','Newspapers':'वृत्तपत्रे','Public movements':'सामाजिक चळवळी','Constitution & law':'संविधान आणि कायदा','Lifetime event':'जीवनातील घटना','Linked archive record':'संबंधित संग्रह नोंद','Historical photograph':'ऐतिहासिक छायाचित्र','Open related record':'संबंधित नोंद उघडा',
'The Media Library':'माध्यम संग्रह','Photograph':'छायाचित्र','Photographs':'छायाचित्रे','Audio':'ध्वनी','Audio recordings':'ध्वनिमुद्रणे','Video':'व्हिडिओ','Videos':'व्हिडिओ','Document':'दस्तऐवज','Documents':'दस्तऐवज','All':'सर्व','Surprise me':'एखादी नोंद सुचवा','Browse by medium':'माध्यमानुसार पाहा','Related record':'संबंधित नोंद','Open original source':'मूळ स्रोत उघडा','Source':'स्रोत','Rights':'वापराचे हक्क','Context before spectacle':'दृश्यांसोबत योग्य संदर्भ',
'SOURCE-LINKED RESEARCH · MULTILINGUAL MUSEUM GUIDE':'मूळ संदर्भांसह संशोधन · बहुभाषिक संग्रहालय मार्गदर्शक','Answering in':'उत्तराची भाषा','Ask the archive':'संग्रहाला विचारा','Reading the archive…':'संग्रहातील संदर्भ तपासत आहे…','Museum voice':'संग्रहालयातील निवेदन','Online neural voice':'नैसर्गिक ऑनलाइन आवाज','Delivery':'निवेदनाची शैली','Museum guide':'संग्रहालय मार्गदर्शक','Conversation':'संभाषण','Calm narration':'शांत निवेदन','Read answers aloud':'उत्तरे मोठ्याने वाचा','End live guide':'थेट संवाद थांबवा','Start live guide':'थेट संवाद सुरू करा','Play narration':'निवेदन ऐका','Stop':'थांबवा','Choose a ready voice answer':'तयार प्रश्नांपैकी एक निवडा','SMRITI ANSWER ·':'SMRITI चे उत्तर ·','Sources in this archive':'या संग्रहातील स्रोत','Original quotation':'मूळ भाषेतील उद्धरण','Translation':'भाषांतर','Listen in':'या भाषेत ऐका:',
'What did Ambedkar mean by social democracy?':'आंबेडकरांना सामाजिक लोकशाही म्हणजे काय अभिप्रेत होते?','Why did Ambedkar criticise caste?':'आंबेडकरांनी जातिव्यवस्थेवर टीका का केली?','What constitutional safeguards did he propose?':'त्यांनी कोणत्या घटनात्मक संरक्षणांची शिफारस केली?','How did Buddhism shape his final work?':'बौद्ध धर्माचा त्यांच्या अखेरच्या कार्यावर काय प्रभाव पडला?',
'MY VISITOR COLLECTION':'माझा वैयक्तिक संग्रह','Compile your journey':'तुमचा वैयक्तिक संग्रह तयार करा','Your collection is empty':'तुमचा संग्रह रिकामा आहे','Add to collection':'संग्रहात जोडा','Saved to collection':'संग्रहात जतन केले','Copy collection link':'संग्रहाची लिंक कॉपी करा','Continue after your visit':'भेटीनंतरही वाचन सुरू ठेवा',
'CURATOR WORKSPACE':'संग्रहपालाचे कार्यक्षेत्र','From scan to trusted record.':'स्कॅनपासून विश्वासार्ह नोंदीपर्यंत.','Ingest':'दस्तऐवज जोडा','Review':'पडताळणी','Approve':'मंजुरी','Publish':'प्रकाशित करा','Title':'शीर्षक','Year':'वर्ष','Source / holding institution':'स्रोत / संग्रह असलेली संस्था','Select rights status':'वापराच्या हक्कांची स्थिती निवडा','Public domain':'सार्वजनिक मालकी','Institution licensed':'संस्थेची वापरपरवानगी','Restricted research access':'मर्यादित संशोधन प्रवेश','Corrected transcription':'दुरुस्त केलेला मजकूर','Clear draft':'मसुदा पुसा','Approve record':'नोंदीला मंजुरी द्या','Publish to archive':'संग्रहात प्रकाशित करा','Document title':'दस्तऐवजाचे शीर्षक','Choose a scanned page':'स्कॅन केलेले पान निवडा','Run OCR on this scan':'या स्कॅनमधील मजकूर ओळखा','Source reference':'मूळ स्रोताचा संदर्भ','ABOUT THIS RECORD':'या नोंदीविषयी','TAKE THE ARCHIVE WITH YOU':'संग्रह तुमच्यासोबत ठेवा','Install SMRITI AI':'SMRITI AI इन्स्टॉल करा','Install on this device':'या उपकरणावर इन्स्टॉल करा','Installed':'इन्स्टॉल केले','Archive':'संग्रह','Timeline':'कालक्रम','Research':'संशोधन','Retry':'पुन्हा प्रयत्न करा','Translation unavailable. Original text is shown.':'भाषांतर उपलब्ध नाही. मूळ मजकूर दाखवला आहे.',
},
'hi':{
'Explore archive':'संग्रह खोजें','History map':'इतिहास यात्रा','Media library':'मीडिया संग्रह','Research assistant':'शोध सहायक','Institution console':'संस्था प्रबंधन','Install app':'ऐप इंस्टॉल करें','Choose language':'भाषा चुनें','AMBEDKAR DIGITAL ARCHIVE':'आंबेडकर डिजिटल संग्रह',
'KNOWLEDGE · JUSTICE · MEMORY':'ज्ञान · न्याय · स्मृति','Ideas that shaped':'आधुनिक भारत को','modern India.':'आकार देने वाले विचार।','Explore the writings, speeches and constitutional vision of Dr. B. R. Ambedkar through a living, evidence-led digital archive.':'डॉ. बाबासाहेब आंबेडकर के लेखन, भाषणों और संवैधानिक विचारों को मूल संदर्भों सहित इस डिजिटल संग्रह में जानें।','Search speeches, ideas, dates…':'भाषण, विचार या तारीखें खोजें…','Explore':'खोजें','Begin with':'यहाँ से शुरू करें','Constitution':'संविधान','Social democracy':'सामाजिक लोकतंत्र','Annihilation of Caste':'जाति का उन्मूलन','Educate,':'शिक्षित बनो,','agitate,':'संघर्ष करो,','organise.':'संगठित रहो।',
'Ask SMRITI':'SMRITI से पूछें','Museum voice':'संग्रहालय का कथावाचन','Delivery':'कथावाचन शैली','Museum guide':'संग्रहालय मार्गदर्शक','Conversation':'बातचीत','Calm narration':'शांत कथावाचन','Read answers aloud':'उत्तर सुनाएँ','Start live guide':'लाइव संवाद शुरू करें','End live guide':'लाइव संवाद बंद करें','Play narration':'कथावाचन सुनें','Online neural voice':'स्वाभाविक ऑनलाइन आवाज़','Choose a ready voice answer':'तैयार प्रश्नों में से चुनें','Ask the archive':'संग्रह से पूछें','Reading the archive…':'संग्रह के संदर्भ जाँचे जा रहे हैं…','Original quotation':'मूल भाषा का उद्धरण','Sources in this archive':'इस संग्रह के स्रोत','Stop':'रोकें','Retry':'दोबारा प्रयास करें','Translation unavailable. Original text is shown.':'अनुवाद उपलब्ध नहीं है। मूल पाठ दिखाया जा रहा है।','The Media Library':'मीडिया संग्रह','Explore the archive':'संग्रह खोजें','Search by title, theme or date…':'शीर्षक, विषय या तारीख से खोजें…','All records':'सभी अभिलेख','Saved to collection':'संग्रह में सहेजा गया','Add to collection':'संग्रह में जोड़ें','Your collection is empty':'आपका संग्रह खाली है','Compile your journey':'अपना संग्रह तैयार करें','CURATOR WORKSPACE':'संग्रहपाल का कार्यक्षेत्र','From scan to trusted record.':'स्कैन से विश्वसनीय अभिलेख तक।','The lifetime history map':'जीवन यात्रा और इतिहास','Photographs':'तस्वीरें','Audio recordings':'ध्वनि रिकॉर्डिंग','Videos':'वीडियो','Documents':'दस्तावेज़',
}}
overrides['mr'].update({
'Open navigation':'नेव्हिगेशन उघडा','Close navigation':'नेव्हिगेशन बंद करा','Speaker':'आवाज','Voice type':'आवाज निवडा','Female':'स्त्रीचा आवाज','Male':'पुरुषाचा आवाज','Original speaker':'मूळ आवाज','Preview voice':'आवाज ऐकून पाहा','Refresh voices':'आवाजांची उपलब्धता तपासा','Narration style':'कथनशैली','Local neural voice':'स्थानिक नैसर्गिक आवाज','AI4Bharat demo · shared capacity':'AI4Bharat प्रात्यक्षिक · सामायिक सेवा','Text and voice':'मजकूर आणि आवाज','Text only · voice model needed':'मजकूर उपलब्ध · आवाजाचे मॉडेल आवश्यक','No voice installed':'आवाजाचे मॉडेल उपलब्ध नाही','Text available · voice not installed':'मजकूर उपलब्ध · आवाजाचे मॉडेल नाही',
'Welcome to SMRITI AI. Let us explore Dr. B. R. Ambedkar’s ideas together.':'SMRITI AI मध्ये तुमचे स्वागत आहे. चला, डॉ. बाबासाहेब आंबेडकरांचे विचार एकत्र जाणून घेऊया.',
'Choose a speaker and preview the voice before listening to an answer.':'उत्तर ऐकण्यापूर्वी तुमचा आवडता आवाज निवडा आणि ऐकून पाहा.',
'This language has one original speaker. Male and female choices are available in other languages.':'या भाषेसाठी एक मूळ आवाज उपलब्ध आहे. इतर भाषांमध्ये स्त्री आणि पुरुषांचे आवाज निवडता येतात.',
'This prototype voice uses AI4Bharat’s public demo. Availability depends on its free quota.':'हा आवाज AI4Bharat च्या सार्वजनिक प्रात्यक्षिक सेवेतून येतो. उपलब्धता त्या सेवेच्या मोफत मर्यादेवर अवलंबून आहे.',
'Experimental voice: pronunciation needs native-speaker review.':'प्रायोगिक आवाज: उच्चारांची त्या भाषेतील जाणकारांनी पडताळणी करणे आवश्यक आहे.',
'Online narration sends the spoken text to Microsoft’s speech service.':'ऑनलाइन कथनासाठी मजकूर Microsoft च्या ध्वनी सेवेकडे पाठवला जातो.',
'You can read answers in this language. Its voice model is not installed yet.':'या भाषेत उत्तरे वाचता येतात. आवाजाचे मॉडेल अद्याप उपलब्ध नाही.',
'Microphone input is not supported for this language. Please type your question.':'या भाषेत मायक्रोफोनवरून प्रश्न विचारण्याची सुविधा नाही. कृपया प्रश्न लिहा.',
'Museum guide is speaking.':'संग्रहालय मार्गदर्शक बोलत आहे.','Narration finished.':'कथन पूर्ण झाले.','Voice availability updated.':'आवाजांची उपलब्धता तपासली.','No installed voice for this language. You can still read the translated answer.':'या भाषेसाठी आवाज उपलब्ध नाही. भाषांतरित उत्तर वाचता येईल.'
})
overrides['hi'].update({
'Open navigation':'नेविगेशन खोलें','Close navigation':'नेविगेशन बंद करें','Speaker':'आवाज़','Voice type':'आवाज़ चुनें','Female':'महिला की आवाज़','Male':'पुरुष की आवाज़','Original speaker':'मूल आवाज़','Preview voice':'आवाज़ सुनकर देखें','Refresh voices':'आवाज़ों की उपलब्धता जाँचें','Narration style':'कथावाचन शैली','Local neural voice':'स्थानीय स्वाभाविक आवाज़','AI4Bharat demo · shared capacity':'AI4Bharat डेमो · साझा सेवा','Text and voice':'पाठ और आवाज़','Text only · voice model needed':'पाठ उपलब्ध · आवाज़ का मॉडल चाहिए','No voice installed':'आवाज़ का मॉडल उपलब्ध नहीं','Text available · voice not installed':'पाठ उपलब्ध · आवाज़ का मॉडल नहीं',
'Welcome to SMRITI AI. Let us explore Dr. B. R. Ambedkar’s ideas together.':'SMRITI AI में आपका स्वागत है। आइए, डॉ. बाबासाहेब आंबेडकर के विचारों को साथ मिलकर जानें।',
'Choose a speaker and preview the voice before listening to an answer.':'उत्तर सुनने से पहले अपनी पसंद की आवाज़ चुनें और सुनकर देखें।',
'This prototype voice uses AI4Bharat’s public demo. Availability depends on its free quota.':'यह आवाज़ AI4Bharat की सार्वजनिक डेमो सेवा से आती है। उपलब्धता उस सेवा की मुफ्त सीमा पर निर्भर है।',
'Experimental voice: pronunciation needs native-speaker review.':'प्रायोगिक आवाज़: उच्चारण की इस भाषा के जानकारों से जाँच ज़रूरी है।',
'Online narration sends the spoken text to Microsoft’s speech service.':'ऑनलाइन कथावाचन के लिए पाठ Microsoft की ध्वनि सेवा को भेजा जाता है।',
'Microphone input is not supported for this language. Please type your question.':'इस भाषा में माइक्रोफोन से प्रश्न पूछने की सुविधा नहीं है। कृपया प्रश्न लिखें।',
'Museum guide is speaking.':'संग्रहालय मार्गदर्शक बोल रहा है।','Narration finished.':'कथावाचन पूरा हुआ।','Voice availability updated.':'आवाज़ों की उपलब्धता जाँच ली गई।'
})
overrides['mr'].update({'Voice & research': 'आवाजातून संवाद आणि संशोधन', 'Talk to SMRITI': 'SMRITI शी बोला', 'Your museum guide': 'तुमचा संग्रहालय मार्गदर्शक', 'Choose a voice. Listen at your pace.': 'आवाज निवडा. तुमच्या गतीने ऐका.', 'Ask with your voice': 'बोलून प्रश्न विचारा', 'Send question': 'प्रश्न पाठवा', 'About this voice': 'या आवाजाविषयी', 'A generated museum guide, not a historical recording of Dr. Ambedkar.': 'हे कृत्रिम आवाजातील मार्गदर्शक निवेदन आहे; डॉ. आंबेडकरांचे मूळ ध्वनिमुद्रण नाही.', 'Original source': 'मूळ स्रोत', 'Open original PDF': 'मूळ PDF उघडा', 'Source website': 'स्रोताचे संकेतस्थळ', 'Original PDF': 'मूळ PDF', 'READ THE ORIGINALS': 'मूळ लेखन वाचा', 'Writings & Speeches': 'लेखन आणि भाषणे', 'Official collection': 'अधिकृत संग्रह', 'Official editions. Original PDFs. Direct institutional links.': 'अधिकृत आवृत्त्या आणि मूळ PDF — संस्थेच्या संकेतस्थळावरील थेट दुवे.', 'SMRITI’s summary is separate from the original document. PDFs open on the institution’s website.': 'SMRITI चा सारांश आणि मूळ दस्तऐवज वेगळे आहेत. PDF संबंधित संस्थेच्या संकेतस्थळावर उघडेल.', 'No original PDF has been attached to this institutional record.': 'या संस्थात्मक नोंदीसोबत मूळ PDF जोडलेली नाही.'})
overrides['hi'].update({'Voice & research': 'आवाज़ से संवाद और शोध', 'Talk to SMRITI': 'SMRITI से बात करें', 'Your museum guide': 'आपका संग्रहालय मार्गदर्शक', 'Choose a voice. Listen at your pace.': 'आवाज़ चुनें। अपनी गति से सुनें।', 'Ask with your voice': 'बोलकर प्रश्न पूछें', 'Send question': 'प्रश्न भेजें', 'About this voice': 'इस आवाज़ के बारे में', 'A generated museum guide, not a historical recording of Dr. Ambedkar.': 'यह कृत्रिम आवाज़ में मार्गदर्शक कथावाचन है; डॉ. आंबेडकर की मूल रिकॉर्डिंग नहीं है।', 'Original source': 'मूल स्रोत', 'Open original PDF': 'मूल PDF खोलें', 'Source website': 'स्रोत की वेबसाइट', 'Original PDF': 'मूल PDF', 'READ THE ORIGINALS': 'मूल लेखन पढ़ें', 'Writings & Speeches': 'लेखन और भाषण', 'Official collection': 'आधिकारिक संग्रह', 'Official editions. Original PDFs. Direct institutional links.': 'आधिकारिक संस्करण और मूल PDF — संस्था की वेबसाइट के सीधे लिंक।', 'SMRITI’s summary is separate from the original document. PDFs open on the institution’s website.': 'SMRITI का सारांश मूल दस्तावेज़ से अलग है। PDF संबंधित संस्था की वेबसाइट पर खुलेगी।', 'No original PDF has been attached to this institutional record.': 'इस संस्थागत अभिलेख के साथ मूल PDF नहीं जोड़ी गई है।'})
overrides['mr'].update({'Ask a question in your own voice. Explore Babasaheb’s ideas with a calm guide and open the original documents behind each answer.': 'तुमचा प्रश्न बोलून विचारा. शांत निवेदनातून बाबासाहेबांचे विचार जाणून घ्या आणि उत्तरासोबत दिलेले मूळ दस्तऐवज वाचा.', 'Curated guide summary. Verify interpretation against the linked original documents.': 'हा मार्गदर्शक सारांश आहे. अर्थ आणि संदर्भांची खात्री करण्यासाठी जोडलेले मूळ दस्तऐवज वाचा.', 'Ask a question. Hear a calm, source-linked answer.': 'प्रश्न विचारा. मूळ संदर्भांसह शांत उत्तर ऐका.'})
overrides['hi'].update({'Ask a question in your own voice. Explore Babasaheb’s ideas with a calm guide and open the original documents behind each answer.': 'अपना प्रश्न बोलकर पूछें। शांत कथावाचन में बाबासाहेब के विचार जानें और उत्तर के साथ दिए गए मूल दस्तावेज़ पढ़ें।', 'Curated guide summary. Verify interpretation against the linked original documents.': 'यह मार्गदर्शक सारांश है। अर्थ और संदर्भ की पुष्टि के लिए जुड़े हुए मूल दस्तावेज़ पढ़ें।', 'Ask a question. Hear a calm, source-linked answer.': 'प्रश्न पूछें। मूल संदर्भों के साथ शांत उत्तर सुनें।'})
for language,updates in overrides.items():
 path=root/f'public/locales/{language}.json';messages=json.loads(path.read_text());messages.update(updates);path.write_text(json.dumps(messages,ensure_ascii=False,indent=2)+'\n')
